# Generated by Django 3.0.5 on 2020-04-08 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('Likes', models.IntegerField()),
                ('Dislikes', models.IntegerField()),
                ('Resolved', models.BooleanField(default=False)),
                ('Theme', models.CharField(choices=[('Sport', 'Sport'), ('Science', 'Science'), ('Art', 'Art')], max_length=20)),
                ('Pub_Date', models.DateTimeField()),
                ('Last_Modif', models.DateTimeField()),
                ('Pub_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
    ]
