# Generated by Django 3.0.5 on 2020-04-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_auto_20200408_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='Dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publication',
            name='Last_Modif',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publication',
            name='Pub_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
